---
- name: Copy Bash Folder
  become: false
  copy:
    src: ../bash/
    dest: "{{ lookup('env','HOME') }}/.bash"

- name: Add source to .bashrc
  blockinfile:
    create: true
    marker: "# ANISBLE .bashrc INCLUDE"
    name: "{{ lookup('env','HOME') }}/.bashrc"
    block: |
      source .bash/bash_include.sh