---
- name: Install Cargo
  package:
    name: "cargo"
    state: present

- name: Install CMake
  package:
    name: "cmake"
    state: present

# Loop with conditional doesn't work well, cargo is silly and fails if the package is already installed -_-

- name: Install Cargo Packages
  shell: test -z $(which {{ item }}) && cargo install {{ item }} || true
  with_list:
    - exa
    - bat
    - tldr