---
- name: Install Cargo
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: Install CMake
  package:
    name: "cmake"
    state: present

- name: Install OpenSSL Packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - libssl-dev
      - pkg-config

# Loop with conditional doesn't work well, cargo is silly and fails if the package is already installed -_-

- name: Install Cargo Packages
  shell: test -z $(which {{ item }}) && cargo install {{ item }} || true
  with_list:
    - exa
    - bat
    - tealdeer

- name: Update TLDR
  shell: tldr --update