---
- name: Install Snap
  package:
    name: "snapd"
    state: present

- name: Install Snap Packages
  command: snap install {{ item }} --classic
  loop:
    - slack
    - spotify
    - phpstorm
    - intellij-idea-ultimate